name: Build and Deploy

permissions:
  contents: write
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  build:
    environment: github-pages
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm ci

      - run: npm run build
      
      - name: Publish
        env:
          NPM_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
        run: |
          npm publish
          